databases:
  - name: build_login_page
    databaseName: build_login_page
    user: build_login_page

services:
  - type: web
    name: build_login_page
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: build_login_page
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false